---
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - discovery.type=single-node
    container_name: elasticsearch
    volumes:
      - esdata1:/home/rlopessilva/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
volumes:
  esdata1:
    driver: local